### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MenacingPerson** [MathisP75/daemon-dotfiles#1]
Hey there! I'm making an AUR package for this. I noticed you don't have a LICENSE, could you add it please? Thanks

**Comment by MenacingPerson** [comment]
Oh, and a description on github as well?

![image](https://user-images.githubusercontent.com/59611020/193400459-d33c369f-7486-4f81-82bc-b9ba339fd4a0.png)

Edit: https://aur.archlinux.org/packages/kvantum-theme-daemon-git
https://aur.archlinux.org/packages/kdeplasma-themes-daemon-git

I made one.
The license=gpl is a default option, you can ignore it. I will fix it if you update with a license

**Comment by MathisP75** [comment]
Oh wow, I don't know a lot about licenses, I will read about them more and update it. That's awesome!

**Comment by MathisP75** [comment]
I added a GPL license

**Comment by MenacingPerson** [comment]
![image](https://user-images.githubusercontent.com/59611020/193419207-803d44b0-36bb-4509-811e-f427ab17a403.png)

Typo

**Comment by MathisP75** [comment]
Fixed it

**Comment by MenacingPerson** [comment]
Thank you
